name: Lint Python Code

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | bash

      - name: Add Pixi to PATH
        run: echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Verify Pixi
        run: pixi --version

      - name: Install dependencies
        run: pixi install

      - name: Run Ruff
        run: pixi run ruff check --output-format=github
